//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modwana.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modwana.Core.Resources.ValidationText", typeof(ValidationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل ({0}) لا يتطابق مع حقل ({1}).
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال البريد الالكتروني بطريقة صحيحة.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية يجب ان يكون بعد تاريخ البداية.
        /// </summary>
        public static string EndDateMustBeGreateThanStartDate {
            get {
                return ResourceManager.GetString("EndDateMustBeGreateThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير معروف.
        /// </summary>
        public static string Identity_DefaultError {
            get {
                return ResourceManager.GetString("Identity_DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الاكتروني موجود مسبقاً.
        /// </summary>
        public static string Identity_DuplicateEmail {
            get {
                return ResourceManager.GetString("Identity_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحية مسجلة مسبقاً.
        /// </summary>
        public static string Identity_DuplicateRoleName {
            get {
                return ResourceManager.GetString("Identity_DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم موجود مسبقاً.
        /// </summary>
        public static string Identity_DuplicateUserName {
            get {
                return ResourceManager.GetString("Identity_DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني غير صحيح.
        /// </summary>
        public static string Identity_InvalidEmail {
            get {
                return ResourceManager.GetString("Identity_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الصلاحية غير صحيح.
        /// </summary>
        public static string Identity_InvalidRoleName {
            get {
                return ResourceManager.GetString("Identity_InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز غير صحيح.
        /// </summary>
        public static string Identity_InvalidToken {
            get {
                return ResourceManager.GetString("Identity_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم غير صحيح.
        /// </summary>
        public static string Identity_InvalidUserName {
            get {
                return ResourceManager.GetString("Identity_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم مسجل دخول مسبقاً.
        /// </summary>
        public static string Identity_LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("Identity_LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة.
        /// </summary>
        public static string Identity_PasswordMismatch {
            get {
                return ResourceManager.GetString("Identity_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب ان تحتوي على رقم.
        /// </summary>
        public static string Identity_PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("Identity_PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب ان تحتوي على حرف صغير.
        /// </summary>
        public static string Identity_PasswordRequiresLower {
            get {
                return ResourceManager.GetString("Identity_PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب ان تحتوي على رمز.
        /// </summary>
        public static string Identity_PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("Identity_PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب ان تحتوي على حروف مختلفة.
        /// </summary>
        public static string Identity_PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("Identity_PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب ان تحتوي على حرف كبير.
        /// </summary>
        public static string Identity_PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("Identity_PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور قصيرة.
        /// </summary>
        public static string Identity_PasswordTooShort {
            get {
                return ResourceManager.GetString("Identity_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم يوجد لديه كلمة مرور مسبقة.
        /// </summary>
        public static string Identity_UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("Identity_UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم لديه الصلاحية مسبقا.
        /// </summary>
        public static string Identity_UserAlreadyInRole {
            get {
                return ResourceManager.GetString("Identity_UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب المستخدم مقفل.
        /// </summary>
        public static string Identity_UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("Identity_UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم لا توجد لديه الصلاحية.
        /// </summary>
        public static string Identity_UserNotInRole {
            get {
                return ResourceManager.GetString("Identity_UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل ({0}) مطلوب..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال رقم جوال صحيح مثال: (5xxxxxxx).
        /// </summary>
        public static string SaudiMobile {
            get {
                return ResourceManager.GetString("SaudiMobile", resourceCulture);
            }
        }
    }
}
